version: "3.7"

services:
  regression:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
      - ./allure-report:/usr/workspace/allure-report   # 👈 проброс отчёта
    command: pytest -sv -m need_review --alluredir=allure-results
    working_dir: /usr/workspace
    environment:
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
