version: 2.1
jobs:
  build:
    resource_class: 'windows.medium'
    machine:
      image: 'windows-server-2022-gui:current'
      shell: 'powershell.exe -ExecutionPolicy RemoteSigned'
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Download Selenium Server
          command: | 
            Invoke-WebRequest -Uri "https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.19.0/selenium-server-4.19.1.jar" -OutFile "selenium-server-standalone.jar"
#      - run:
#          name: Download allure
#          command: |
#            Invoke-WebRequest -Uri "https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.zip" -OutFile "allure-2.29.0.zip"
      - run:
          name: Install Scoop
          command: |
            Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
            Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
      - run:
          name: Install allure
          command: |
            scoop install allure
#      - run:
#          name: Unpack allure
#          command: |
#            Expand-Archive allure-2.29.0.zip -DestinationPath C:\Users\circleci\repo\allure-2.29.0
#            Get-Location
#      - run:
#          name: Add allure to sys path
#          command: |
#            $newPath = "$env:PATH;C:\Users\circleci\repo\allure-2.29.0\allure-2.29.0\bin"
#            [System.Environment]::SetEnvironmentVariable("PATH", $newPath, [System.EnvironmentVariableTarget]::Machine)
#            echo $env:path
      - run:
          name: Run Selenium Server
          command: |
            java -jar selenium-server-standalone.jar standalone --selenium-manager true
          background: true
      - run:
          name: check python
          command: python --version
      - run:
          name: create venw
          command: python -m venv venv
      - run:
          name: activate venw
          command: .\venv\Scripts\activate
      - run:
          name: upgrade pip
          command: python -m pip install --upgrade pip
      - run:
          name: install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            echo $env:path
            pytest -rP -m need_review
      - store_artifacts:
          path: tmp/screenshots/
      - store_artifacts:
          path: C:\ProgramData\chocolatey\logs\chocolatey.log