version: 2.1
jobs:
  build:
    resource_class: 'windows.medium'
    machine:
      image: 'windows-server-2022-gui:current'
      shell: 'powershell.exe -ExecutionPolicy Bypass'
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install ChromeDriver
          command: |
            $chrmVer = (Get-WmiObject Win32_Product | Where-Object { $_.Name -match "Google Chrome" }).Version
            $majorVersion = $chrmVer.split(".")[0]
            $url = "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$majorVersion"
            Invoke-WebRequest -Uri $url -OutFile chromedriver_version.txt
            $chromedriverVersion = Get-Content chromedriver_version.txt
            Invoke-WebRequest "https://chromedriver.storage.googleapis.com/$chromedriverVersion/chromedriver_win32.zip" -OutFile chromedriver.zip
            Expand-Archive chromedriver.zip -DestinationPath $env:USERPROFILE
            $env:PATH += ";$env:USERPROFILE"
      - run:
          name: Run Selenium Server
          command: |
            java -jar C:\tools\selenium\selenium-server-standalone.jar
          background: true
      - run:
          name: check python
          command: python --version
      - run:
          name: create venw
          command: python -m venv venv
      - run:
          name: activate venw
          command: .\venv\Scripts\activate
      - run:
          name: upgrade pip
          command: python -m pip install --upgrade pip
      - run:
          name: install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            pytest -rP -m need_review
      - store_artifacts:
          path: tmp/screenshots/
      - store_artifacts:
          path: C:\ProgramData\chocolatey\logs\chocolatey.log
