      - run:
          name: Run Selenium Server
          command: |
            java -jar C:\tools\selenium\selenium-server-standalone.jar
          background: true
      - run:
          name: check python
          command: python --version
      - run:
          name: create venw
          command: python -m venv venv
      - run:
          name: activate venw
          command: .\venv\Scripts\activate
      - run:
          name: upgrade pip
          command: python -m pip install --upgrade pip
      - run:
          name: install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            pytest -rP -m need_review
      - store_artifacts:
          path: tmp/screenshots/