version: 2
orbs:
  win: circleci/windows@5.0.0
jobs:
  build:
    executor:
      name: win/default
      size: "medium"
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install python
          command: choco install python3
      - run:
          name: create venw
          command: python3 -m venv venv
      - run:
          name: activate venw
          command: . venv/bin/activate
      - run:
          name: upgrade pip
          command: pip install --upgrade pip --user
      - run:
          name: install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest -rP -m need_review
      - store_artifacts:
          path: tmp/screenshots/
