version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.11.0
      - image: selenium/standalone-chrome:3.11.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: create venw
          command: python3 -m venv venv
      - run:
          name: activate venw
          command: . venv/bin/activate
      - run:
          name: upgrade pip
          command: pip install --upgrade pip --user
      - run:
          name: install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest -rP -m need_review
      - store_artifacts:
          path: tmp/screenshots/
