version: 2
jobs:
  build:
    resource_class: 'windows.medium'
    machine:
      image: 'windows-server-2022-gui:current'
      shell: 'powershell.exe -ExecutionPolicy Bypass'
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Download Selenium Server
          command: |
            ls
            mkdir selenium
            cd .\selenium\
            choco install -y selenium
      - run:
          name: go into selenium package
          command: cd selenium
      - run:
          name: Run Selenium Server
          command: |
            ls
            java -jar selenium/selenium-server-standalone.jar
      - run:
          name: check files
          command: ls
      - run:
          name: return to root
          command: cd ..
      - run:
          name: check files
          command: ls
      - run:
          name: check python
          command: python --version
      - run:
          name: create venw
          command: python -m venv venv
      - run:
          name: activate venw
          command: .\venv\Scripts\activate
      - run:
          name: upgrade pip
          command: python -m pip install --upgrade pip
      - run:
          name: install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            pytest -rP -m need_review
      - store_artifacts:
          path: tmp/screenshots/
      - store_artifacts:
          path: C:\ProgramData\chocolatey\logs\chocolatey.log
