version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.8
jobs:
  build:
    resource_class: 'windows.medium'
    machine:
      image: 'windows-server-2022-gui:current'
      shell: 'powershell.exe -ExecutionPolicy Bypass'
    working_directory: ~/repo
    steps:
      - checkout
      - browser-tools/install-browser-tools:
          chrome-version: 85.0.4183.102
      - run:
          name: Download Selenium Server
          command: choco install -y selenium
      - run:
          name: Run Selenium Server
          command: |
            java -jar C:\tools\selenium\selenium-server-standalone.jar
          background: true
      - run:
          name: check python
          command: python --version
      - run:
          name: create venw
          command: python -m venv venv
      - run:
          name: activate venw
          command: .\venv\Scripts\activate
      - run:
          name: upgrade pip
          command: python -m pip install --upgrade pip
      - run:
          name: install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            pytest -rP -m need_review
      - store_artifacts:
          path: tmp/screenshots/
      - store_artifacts:
          path: C:\ProgramData\chocolatey\logs\chocolatey.log
