version: 2.1
jobs:
  build:
    resource_class: 'windows.medium'
    machine:
      image: 'windows-server-2022-gui:current'
      shell: 'powershell.exe -ExecutionPolicy Bypass'
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Download Selenium Server
          command: | 
            Invoke-WebRequest -Uri "https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.19.0/selenium-server-4.19.1.jar" -OutFile "selenium-server-standalone.jar"
      - run:
          name: Download allure
          command: |
            Invoke-WebRequest -Uri "https://github.com/allure-framework/allure2/archive/refs/tags/2.29.0.zip" -OutFile "allure-2.29.0.zip"
      - run:
          name: Unpack allure
          command: |
            Expand-Archive allure-2.29.0.zip -DestinationPath C:\Users\circleci\repo\allure-2.29.0
            Get-Location
      - run:
          name: Check path
          command: |
            cd allure-2.29.0
            ls
            cd allure2-2.29.0
            ls
      - run:
          name: Add allure to sys path
          command: |
            $existingPath = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path", "User")
            $newPath = $existingPath + ";C:\Users\circleci\repo\\allure-2.29.0\allure2-2.29.0.0\bin"
            [System.Environment]::SetEnvironmentVariable("Path", $newPath, "Machine")
            echo $env:path
            $existingPath = [System.Environment]::GetEnvironmentVariable("Path", "User")
            $newPath = $existingPath + ";C:\Users\raind\Downloads\allure-2.29.0\allure2-2.29.0\bin"
            [System.Environment]::SetEnvironmentVariable("Path", $newPath, "User")
            echo $env:path
      - run:
          name: Run Selenium Server
          command: |
            java -jar selenium-server-standalone.jar standalone --selenium-manager true
          background: true
      - run:
          name: check python
          command: python --version
      - run:
          name: create venw
          command: python -m venv venv
      - run:
          name: activate venw
          command: .\venv\Scripts\activate
      - run:
          name: upgrade pip
          command: python -m pip install --upgrade pip
      - run:
          name: install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            pytest -rP -m need_review
      - store_artifacts:
          path: tmp/screenshots/
      - store_artifacts:
          path: C:\ProgramData\chocolatey\logs\chocolatey.log