name: Stepik tests

#on: [ push ]
on: workflow_dispatch


jobs:
  stepik-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout gh-pages to github runner
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Run stepik UI tests via docker compose
        env:
          EMAIL: ${{secrets.EMAIL}}
          PASSWORD: ${{secrets.PASSWORD}}
        run: |
          docker-compose up --build --exit-code-from regression || true

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history


#      - name: Copy history from gh-pages to allure-results
#        run: |
#          sudo mkdir -p allure-results/history
#          sudo cp -R ./.github/gh-pages/history/* allure-results/history/

#      - name: Generate allure report
#        run: |
#          sudo docker-compose run regression /bin/sh -c "allure generate allure-results --clean -o allure-report"

#      - name: Deploy report to Github Pages
#        if: always()
#        uses: JamesIves/github-pages-deploy-action@4.1.5
#        with:
#          token: ${{ secrets.CI_TOKEN }}
#          branch: gh-pages
#          folder: allure-report
#          clean: true

